name: junius-test-workflow-template

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello from junius
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ secrets.DEPLOY_TOKEN }}"
          environment: test
  getDeploymentId:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: juniuszhangserai/getDeploymentById@main
        name: getDeploymentId
        with:
          env-name: "test"
          github-token: "${{ secrets.DEPLOY_TOKEN }}"
      - name: 'Echo download path'
        run: echo ${{steps.getDeploymentId.outputs.deploymentId}}