name: junius-test-workflow-template

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello from junius
