name: needs test

on:
  workflow_dispatch:
    inputs:
      only_deploy:
        required: true
        type: boolean
        default: false 
jobs:
  check:
    runs-on: ubuntu-latest
    environment: uat
    steps:
      - run: echo "build ${{github.event.inputs.only_deploy}}"

  build:
    runs-on: ubuntu-latest
    needs: check
    if: github.event.inputs.only_deploy == 'false'
    steps:
      - run: echo "build"

  test:
    runs-on: ubuntu-latest
    environment: uat
    if: github.event.inputs.only_deploy == 'false'
    needs: build

    steps:
      - run: echo111 "build"

  deploy:
    runs-on: ubuntu-latest
    if: ${{  (github.event.inputs.only_deploy == 'true' && needs.check.result == 'success') || ( github.event.inputs.only_deplo == 'false' && needs.test.result=='success') }}
    needs: [check,test]

    steps:
      - run: echo "deploy"
      - run: echo ${{needs.check.result}}
      - run: echo ${{needs.test.result}}
      - run: echo ${{  (github.event.inputs.only_deploy == 'true' && needs.check.result == 'success' && needs.check.result!='failure' && needs.check.result!='cancelled' )}}
      - run: echo ${{  (github.event.inputs.only_deploy == 'false' && needs.test.result=='success' && needs.test.result!='failure' && needs.test.result!='cancelled') }}
      - run: echo ${{  (github.event.inputs.only_deploy == 'true' && needs.check.result == 'success' && needs.check.result!='failure' && needs.check.result!='cancelled' ) || ( github.event.inputs.only_deplo == 'false' && needs.test.result=='success' && needs.test.result!='failure' && needs.test.result!='cancelled') }}
