name: needs test

on:
  workflow_dispatch:
    inputs:
      only_deploy:
        required: true
        type: boolean
        default: false 
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "build ${{github.event.inputs.only_deploy}}"

  build:
    runs-on: ubuntu-latest
    needs: check
    if: github.event.inputs.only_deploy == 'false'
    steps:
      - run: |
        echo "build"
        exit 1

  test:
    runs-on: ubuntu-latest
    if: github.event.inputs.only_deploy == 'false'
    needs: build

    steps:
      - run: echo "build"

  deploy:
    runs-on: ubuntu-latest
    if: ${{ always() && contains(needs.*.result, 'success') && !(contains(needs.*.result, 'failure')) }}
    needs: [test]

    steps:
      - run: echo "deploy"
