name: needs test

on:
  workflow_dispatch:
    inputs:
      only_deploy:
        required: true
        type: boolean
        default: false 
jobs:
  check:
    runs-on: ubuntu-latest
    environment: uat
    steps:
      - run: echo "build ${{github.event.inputs.only_deploy}}"

  build:
    runs-on: ubuntu-latest
    needs: check
    if: github.event.inputs.only_deploy == 'false'
    steps:
      - run: echo "build"

  test:
    runs-on: ubuntu-latest
    environment: uat
    if: github.event.inputs.only_deploy == 'false'
    needs: build

    steps:
      - run: echo111 "build"

  deploy:
    runs-on: ubuntu-latest
    if: ${{  (github.event.inputs.only_deplo == 'true' && job.check.result == 'success') || ( github.event.inputs.only_deplo == 'false' contains(job.test.result, 'success') && !(contains(job.test.result, 'failure')) }} && !(contains(job.test.result, 'cancelled'))) }}
    needs: [check,test]

    steps:
      - run: echo "deploy"
      - run: echo ${{job.test.status}}
