name: needs test

on:
  workflow_dispatch:
    inputs:
      only_deploy:
        equired: true
        type: boolean
        default: false 
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ inputs.only_deploy == false}}
    steps:
      - run: echo "build"

  test:
    runs-on: ubuntu-latest
    if: ${{ inputs.only_deploy == false}}
    needs: build

    steps:
      - run: echo "build ${{ inputs.only_deploy == false }}"

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]

    steps:
      - run: echo "deploy"
