name: needs test

on:
  workflow_dispatch:
    inputs:
      only_deploy:
        required: true
        type: boolean
        default: false 
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "build ${{inputs.only_deploy}}"

  build:
    runs-on: ubuntu-latest
    needs: check
    if: inputs.only_deploy == 'false'
    steps:
      - run: echo "build"

  test:
    runs-on: ubuntu-latest
    if: inputs.only_deploy == 'false'
    needs: build

    steps:
      - run: echo "build"

  deploy:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [build, test]

    steps:
      - run: echo "deploy"
